export const parkingLotData = [
  { id: 1, size: 0, parked: false, hrs: 0, details: null },
  { id: 2, size: 1, parked: false, hrs: 0, details: null },
  { id: 3, size: 2, parked: false, hrs: 0, details: null },
  { id: 4, size: 0, parked: false, hrs: 0, details: null },
  { id: 5, size: 1, parked: false, hrs: 0, details: null },
  { id: 6, size: 2, parked: false, hrs: 0, details: null },
  { id: 7, size: 0, parked: false, hrs: 0, details: null },
  { id: 8, size: 1, parked: false, hrs: 0, details: null },
  { id: 9, size: 2, parked: false, hrs: 0, details: null },
  { id: 10, size: 0, parked: false, hrs: 0, details: null },
  { id: 11, size: 1, parked: false, hrs: 0, details: null },
  { id: 12, size: 2, parked: false, hrs: 0, details: null },
  { id: 13, size: 0, parked: false, hrs: 0, details: null },
  { id: 14, size: 1, parked: false, hrs: 0, details: null },
  { id: 15, size: 2, parked: false, hrs: 0, details: null },
  { id: 16, size: 0, parked: false, hrs: 0, details: null },
  { id: 17, size: 1, parked: false, hrs: 0, details: null },
  { id: 18, size: 2, parked: false, hrs: 0, details: null },
  { id: 19, size: 0, parked: false, hrs: 0, details: null },
  { id: 20, size: 1, parked: false, hrs: 0, details: null },
]
